source:      .
destination: ./_site
layouts:     ./_layouts
includes:     ./_includes
timezone:    nil

future:      true
show_drafts: nil
pygments:    true

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

podcast_info:
    subscribe_url: http:subscribe
